### ISSUE TITLE
Pipes in expressionProperties ?

### ISSUE THREAD

**Issue by matthieubouvierthales** [formly-js/ng2-formly#58]
It seems that pipes are not supported in expressionProperties.

HTML:

```
{{"Hello" | uppercase}}
      <formly-form [model]="user" [fields]="userFields" [form]="form">
        <div class="login-screen-button-container">
          <button type="submit" class="btn btn-primary" (click)="onSubmit()" [disabled]="false">{{"LOGIN_SUBMIT" | translate}}</button>
        </div>
      </formly-form>
```

JS:
```
this.userFields = [
      {
        // the key to be used in the model values
        // so this will be bound to user.username
        key: 'username',
        type: 'input-inline',
        templateOptions: {
          label: this._translateService.instant('LOGIN_LOGIN'),
          placeholder: this._translateService.instant('LOGIN_LOGIN_PLACEHOLDER'),
          focus: true
        },
        expressionProperties: {
          'templateOptions.label': 'TODO',
          'templateOptions.placeholder': '"Hello" | uppercase'
        },
        validation: Validators.compose([Validators.required, Validators.minLength(1)])
      },
      {
        key: 'password',
        type: 'input-inline',
        templateOptions: {
          type: 'password',
          label: this._translateService.instant('LOGIN_PASSWORD'),
          placeholder: this._translateService.instant('LOGIN_PASSWORD_PLACEHOLDER')
        },
        expressionProperties: {
          'templateOptions.label': 'TODO',
          'templateOptions.placeholder': 'TODO',
         'templateOptions.disabled': '!model.username'
        },
        validation: Validators.compose([Validators.required, Validators.minLength(1)])
      }
    ];
```

The "Hello" string is well uppercased in HTML but the placeholder raise an error in console:

```
ng2-formly.js:26 ReferenceError: uppercase is not defined
    at FormlyField.eval (eval at evalExpression (http://localhost:3000/angular2/ng2-formly-custom/bundles/ng2-formly.js:23:113), <anonymous>:3:18)
    at ModuleRecord.evalExpression (http://localhost:3000/angular2/ng2-formly-custom/bundles/ng2-formly.js:23:116)
    at FormlyFieldExpressionDelegate.checkExpressionChange (http://localhost:3000/angular2/ng2-formly-custom/bundles/ng2-formly.js:97:75)
    at FormlyField.FormlyCommon.ngDoCheck (http://localhost:3000/angular2/ng2-formly-custom/bundles/ng2-formly.js:273:45)
    at DebugAppView._View_FormlyForm2.detectChangesInternal (FormlyForm.template.js:313:47)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/angular2/@angular/core/src/linker/view.js:200:14)
    at DebugAppView.detectChanges (http://localhost:3000/angular2/@angular/core/src/linker/view.js:289:44)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3000/angular2/@angular/core/src/linker/view.js:215:37)
    at DebugAppView._View_FormlyForm1.detectChangesInternal (FormlyForm.template.js:199:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/angular2/@angular/core/src/linker/view.js:200:14)
```

The exception appeared when I tried to use "translate" pipe from ng2-translate but there is the same behavior from "uppercase" pipe from angular2.

**Comment by mohammedzamakhan** [comment]
Use Pipes in the the ts rather than sending them into expressionProperties

http://stackoverflow.com/a/35144872

**Comment by matthieubouvierthales** [comment]
Hello,

If I understand your answer, I should use pipe in my ts file like this:
```
var pipe = new DatePipe();
    var self = this;
    setInterval(function() {
      self.test.setTime( self.test.getTime() + 86400000 );
      self.test2.test = self.test2.test + '*';
    }, 1000);

    this.userFields = [
      {
        key: 'password',
        type: 'input',
        templateOptions: {
          type: 'password',
          label: this.test2.test,
          placeholder: pipe.transform(this.test, 'yyyy-MM-dd')
        },
        validation: Validators.compose([Validators.required, Validators.minLength(1)])
      }
    ];
```

It could be a good solution, but:
- the label and placeholder are not dynamically updated (for language change for example).
- the pipes are available in angular formly expressionProperties and a good way, in my opinion, to manage dynamic updates.

**Comment by matthieubouvierthales** [comment]
Hello,

I'm not sure that my last comment was read.
I think that issue must be reopened or an enhancement has to be created.

**Comment by divyakumarjain** [comment]
Pipes supported in Angular view teamplates only in Angular 2.x. Expression engine with Pipe evaluation is not a service which can be consumed in Angular 2.x as against AngularJs 1.x. For getting these kind of features I think one need to use to Javascript or Typescript features and standard API.

**Comment by divyakumarjain** [comment]
I suggest we close this issue as Typescript or Javascript does not supports pipes and also angular 2 compiler is not available as service for compilation of pipes as mention in my previous comment. We can reopen this issue if there is any way to evaluate pipe based expressions.
