### ISSUE TITLE
EXCEPTION: No Directive annotation found on FormlyForm

### ISSUE THREAD

**Issue by crouti** [formly-js/ng2-formly#66]
Hi there,

Just setup ng2-formly with IonicV2 like this:

```
import {Component} from '@angular/core';
import {Platform, ionicBootstrap} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {TabsPage} from './pages/tabs/tabs';
import {FormlyForm, FormlyConfig, FormlyMessages, TemplateDirectives, FormlyProviders} from 'ng2-formly';
import {HTTP_PROVIDERS} from '@angular/http';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';

@Component({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
  directives: [FormlyForm],
  providers: [FormlyConfig, FormlyMessages],
})
export class MyApp {

  private rootPage:any;

  constructor(private platform:Platform) {
    this.rootPage = TabsPage;

    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
    });
  }
}

ionicBootstrap(MyApp, [HTTP_PROVIDERS, FormlyProviders])
```

But it raises an error when launching in web browser with serve -c 

```
ionic $ 0     913800   group    EXCEPTION: No Directive annotation found on FormlyForm
1     913801   error    EXCEPTION: No Directive annotation found on FormlyForm
2     913802   groupEnd 
3     913808   group    EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on FormlyForm
4     913808   error    EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on FormlyForm
5     913809   error    STACKTRACE:
6     913810   error    Error: Uncaught (in promise): No Directive annotation found on FormlyForm
    at resolvePromise (http://localhost:8100/build/js/zone.js:538:32)
    at http://localhost:8100/build/js/zone.js:574:18
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/zone.js:356:38)
    at Object.onInvokeTask (http://localhost:8100/build/js/app.bundle.js:35330:41)
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/zone.js:355:43)
    at Zone.runTask (http://localhost:8100/build/js/zone.js:256:48)
    at drainMicroTaskQueue (http://localhost:8100/build/js/zone.js:474:36)
7     913811   groupEnd 
8     913813   error    Unhandled Promise rejection:, No Directive annotation found on FormlyForm, ; Zone:, angular, ; Task:, Promise.then, ; Value:, [object Object]
9     913814   error    Unhandled Promise rejection:, No Directive annotation found on FormlyForm, ; Zone:, <root>, ; Task:, Promise.then, ; Value:, [object Object]
```

Any idea ?
Thank you very much

**Comment by dschoeni** [comment]
Can confirm this issue after upgrading to angular2-rc4. Any idea where this issue could be caused? I have checked the changelogs of rc4 and not found any hints why this broke ng2-formly.

**Comment by gnovotny** [comment]
ng2-formly has outdated dependencies. Removing or renaming the node_modules folder inside of the ng2-formly folder will solve this issue.

**Comment by crouti** [comment]
Thank you guys for your help, i've just upgrade to angular2-rc4 (changing my package.json dependancies), then rename the node_modules inside of ng2-formly, as well as upgrade its package.json in order to depend on angular2-rc4, and now here's the error at launch (still with ionic serve -c):

`3     704490   group    EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./HomePage class HomePage_Host - inline template:0:0
ORIGINAL EXCEPTION: TypeError: Cannot read property 'get' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'get' of undefined
    at new HomePage (http://localhost:8100/build/js/app.bundle.js:119:18)
    at DebugAppView._View_HomePage_Host0.createInternal (HomePage.template.js:16:24)
    at DebugAppView.AppView.create (http://localhost:8100/build/js/app.bundle.js:31704:21)
    at DebugAppView.create (http://localhost:8100/build/js/app.bundle.js:31916:44)
    at ComponentFactory.create (http://localhost:8100/build/js/app.bundle.js:30774:36)
    at http://localhost:8100/build/js/app.bundle.js:57164:49
    at ZoneDelegate.invoke (http://localhost:8100/build/js/zone.js:323:29)
    at Object.onInvoke (http://localhost:8100/build/js/app.bundle.js:37350:41)
    at ZoneDelegate.invoke (http://localhost:8100/build/js/zone.js:322:35)
    at Zone.run (http://localhost:8100/build/js/zone.js:216:44)
ERROR CONTEXT:
[object Object]`

Any idea ?
